import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F6F1E8",
  },
  bgOrbTop: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "#D95F47",
    opacity: 0.18,
    top: -60,
    right: -40,
  },
  bgOrbBottom: {
    position: "absolute",
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: "#1E2C3A",
    opacity: 0.12,
    bottom: -90,
    left: -80,
  },
  mark: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#D95F47",
    borderWidth: 3,
    borderColor: "#1E2C3A",
    marginBottom: 20,
    shadowColor: "#7A2E1F",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
    elevation: 10,
  },
  wordmark: {
    fontWeight: "900",
    fontSize: 34,
    letterSpacing: 2.4,
    color: "#1E2C3A",
  },
  tagline: {
    marginTop: 10,
    fontSize: 13,
    letterSpacing: 1.1,
    color: "#6B5A4B",
    textTransform: "uppercase",
  },
});
